import {Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <head>
                <script src="https://kit.fontawesome.com/b1828c9c95.js" crossOrigin="anonymous"></script>
            </head>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
