import "./globals.css";

// Import convection font
const convection = "https://fonts.cdnfonts.com/css/convection";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={convection.className}>{children}</body>
        </html>
    );
}
